sunlightacademy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),
    url(r'^ti-webinar/$', TemplateView.as_view(template_name="ti-webinar.html")),
    #url(r'^webinars/$', TemplateView.as_view(template_name="calendar.html")),
    url(r'', include('sfapp.urls')),
    url(r'', include('training.urls')),
)

training/urls.py
from django.conf.urls import patterns, include, url
from training.views import ModuleView, RegisterPlusView

urlpatterns = patterns('',
    url(r'^$', 'training.views.dashboard', name='dashboard'),
    url(r'^account/$', 'training.views.account', name='account'),
    url(r'^account/delete/$', 'training.views.delete_account', name='delete_account'),
    url(r'^account/error/$', 'training.views.account_error', name='account_error'),
    url(r'^account/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^account/setup/$', 'training.views.setup_account', name='setup_account'),
    url(r'^account/register/$', RegisterPlusView.as_view()),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^account/', include('social_auth.urls')),
    url(r'^category/(?P<slug>[\w\-]+)/$', 'training.views.category', name='training_category'),
    url(r'^module/(?P<slug>[\w\-]+)/$', ModuleView.as_view(), name='training_module'),
    url(r'^module/(?P<slug>[\w\-]+)/feedback/$', 'training.views.module_feedback', name='training_module_feedback'),
    url(r'^module/(?P<slug>[\w\-]+)/mark/$', 'training.views.module_mark', name='training_module_mark'),
    url(r'^tagged/(?P<slug>[\w\-]+)/$', 'training.views.tagged', name='tagged'),
    url(r'^events/$', 'training.views.training_list', name='training_list'),
    url(r'^events/(?P<slug>[\w\-]+)/$', 'training.views.training_detail', name='training_detail'),
    url(r'^registrations/$', 'training.views.registrations'),
)

training/forms.py
from django import forms
from django.contrib.auth.models import User
from registration.forms import RegistrationForm

from training.models import Feedback, IS_A_CHOICES

attrs_dict = {'class': 'required'}


class ProfileForm(forms.Form):

    phone = forms.CharField(required=False, max_length=24)
    organization = forms.CharField(required=False, max_length=128)
    is_a = forms.ChoiceField(required=False, choices=IS_A_CHOICES)
    interests = forms.CharField(required=False, widget=forms.Textarea)
    notify = forms.BooleanField(required=False, initial=True)


class UniqueEmailRegistrationForm(RegistrationForm, ProfileForm):
    """ Basic registration form that requires unique email addresses.

        Also overrides passwords to retain value on error.
    """

    first_name = forms.CharField(max_length=64, required=False)
    last_name = forms.CharField(max_length=64, required=False)

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs=attrs_dict, render_value=True),
        label="Password")

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs=attrs_dict, render_value=True),
        label="Confirm Password")

    def clean(self):

        cleaned_data = super(UniqueEmailRegistrationForm, self).clean()

        if 'email' in cleaned_data:
            email = cleaned_data['email']
            if User.objects.filter(email=email).exists():
                self._errors['email'] = self.error_class(["Email address has already been used"])
                del cleaned_data['email']

        return cleaned_data


class SettingsForm(ProfileForm):
    """ Form used on account settings page.
    """

    username = forms.CharField(max_length=32)
    first_name = forms.CharField(max_length=64, required=False)
    last_name = forms.CharField(max_length=64, required=False)
    email = forms.EmailField()
    new_password = forms.CharField(required=False, widget=forms.PasswordInput)


class AccountSetupForm(ProfileForm):
    """ Form used during social authentication to set account preferences.
    """

    username = forms.CharField(max_length=64)
    first_name = forms.CharField(max_length=64)
    last_name = forms.CharField(max_length=64)
    email = forms.EmailField()

    def clean(self):

        cleaned_data = super(AccountSetupForm, self).clean()

        if 'username' in cleaned_data:
            username = cleaned_data['username']
            if User.objects.filter(username=username).exists():
                self._errors['username'] = self.error_class(["Username is already taken"])
                del cleaned_data['username']

        if 'email' in cleaned_data:
            email = cleaned_data['email']
            if User.objects.filter(email=email).exists():
                self._errors['email'] = self.error_class(["Email address has already been used"])
                del cleaned_data['email']

        return cleaned_data


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ('timestamp',)

sunlightacademy/templates/about.html
{% extends "base-full.html" %}

{% block title %}About Sunlight Academy{% endblock %}

{% block content %}
    <div class="module">
        <div class="module span8">
            <h2>About Sunlight Academy</h2>
            <p>Sunlight Academy is the interactive training portal of Sunlight Foundation and aims to provide instructional and educational resources to advance our goal to make government more transparent and accountable.</p>
            <p>Whether you are an investigative journalist trying to get insight on a complex data set, an activist uncovering the hidden influence behind your issue or a congressional staffer in need of mastering legislative data, our transparency training program will teach you how to better connect the dots and make our tools and resources work for you.</p>
            <p>The training modules in the Sunlight Academy range in teaching format from videos to multimedia presentations that cater to both didactic and experiential learners. Be sure to mark finished modules as “completed” to earn prizes and rewards. If you have any questions, comments or suggestions, please email <a href="mailto:training@sunlightfoundation.com">training@sunlightfoundation.com</a>.</p>
            <p>Sunlight Academy is a project of <a href="http://sunlightfoundation.com">Sunlight Foundation</a> and is generously supported by the <a href="http://www.fordfoundation.org/">Ford Foundation</a>.</p>
        </div>
    </div>
{% endblock %}

sunlightacademy/templates/account.html
{% extends "base-full.html" %}

{% block title %}Account Settings - Sunlight Academy{% endblock %}

{% block content %}

	<div class="row">
        <div class="span12">
            <h2>About You</h2>
        </div>
		<div class="span8">
			<form action="." method="post" class="form-horizontal">
				{% csrf_token %}
				<fieldset class="module">
					<legend>Your account</legend>
					<ul class="pushInward">
						<li>
							{{ form.username.errors }}
							<label for="id_username">Username</label>
							{{ form.username }}
						</li>
						<li>
							{{ form.first_name.errors }}
							<label for="id_first_name">First name</label>
							{{ form.first_name }}
						</li>
						<li>
							{{ form.last_name.errors }}
							<label for="id_phone">Last name</label>
							{{ form.last_name }}
						</li>
						<li>
							{{ form.email.errors }}
							<label for="id_email">Email</label>
							{{ form.email }}
						</li>
						<li>
							{{ form.phone.errors }}
							<label for="id_phone">Phone Number</label>
							{{ form.phone }}
						</li>
						<li>
							{{ form.notify.errors }}
							<label for="id_notify" class="checkbox asInput tip">{{ form.notify }}Receive email updates from Sunlight Academy</label>

						</li>
					</ul>
				</fieldset>
				<fieldset class="module">
					<legend>Change your password</legend>
					<p class="tip">Enter a new password in the field below to change your password</p>
					<ul class="pushInward">
						<li>
							{{ form.new_password.errors }}
							<label for="id_new_password">New password</label>
							{{ form.new_password }}
						</li>
					</ul>
				</fieldset>
				<fieldset class="module">
					<legend>About you</legend>
					<p class="tip">The following information will help us in developing future training modules.</p>
					<ul class="pushInward normalList">
						<li>
							{{ form.organization.errors }}
							<label for="id_organization">Organization</label>
							{{ form.organization }}
						</li>
						<li>
							{{ form.is_a.errors }}
							<label for="id_is_a">What best describes your role?</label>
							{{ form.is_a }}
						</li>
						<li>
							{{ form.interests.errors }}
							<label for="id_interests">What are your areas of interest?</label>
							{{ form.interests }}
						</li>
					</ul>
				</fieldset>
					<input type="submit" value="Update Settings" class="btn btn-sunlight btn-large">
			</form>

		</div>

		<div class="span4">

			<h3>Associated Accounts</h3>
			{% if not request.user.has_usable_password %}
				<div class="alert">
					<p><strong>Warning!</strong> You do not have a password set for this account. We recommend setting a new password in the form to the left in case your associated accounts become disconnected.</p>
				</div>
			{% endif %}

			<p>
				{% if social_auth.twitter %}
					<a class="btn btn-warning" href="{% url 'socialauth_disconnect' 'twitter' %}">
						<i class="icon-remove-circle icon-white"></i>
						Unlink Twitter
					</a>
				{% else %}
					<a class="btn" href="{% url 'socialauth_associate_begin' 'twitter' %}">
						<i class="icon-repeat"></i>
						Link with Twitter
					</a>
				{% endif %}
			</p>

			<p>
				{% if social_auth.facebook %}
					<a class="btn btn-warning" href="{% url 'socialauth_disconnect' 'facebook' %}">
						<i class="icon-remove-circle icon-white"></i>
						Unlink Facebook
					</a>
				{% else %}
					<a class="btn" href="{% url 'socialauth_associate_begin' 'facebook' %}">
						<i class="icon-repeat"></i>
						Link with Facebook
					</a>
				{% endif %}
			</p>

			{% comment %}
			{% with request.user.completions.all.select_related as completions %}
				{% if completions %}
					<h2>Completed Modules</h2>
					<ul>
						{% for completion in completions %}
							<li><a href="{% url 'training_module' completion.module.slug %}">{{ completion.module.title }}</a></li>
						{% endfor %}
					</ul>
				{% endif %}
			{% endwith %}
			{% endcomment %}

		</div>

	</div>


	{% if not request.user.is_staff %}
		<div class="row">
			<div class="span12 well delete-account">
				<p>Permanently delete your account.</p>
				<p><a href="/account/delete/" class="btn btn-danger"><i class="icon-trash icon-white"></i> Delete Account</a></p>
			</div>
		</div>
	{% endif %}

{% endblock %}

sunlightacademy/templates/account_delete.html
{% extends "base-full.html" %}

{% block title %}Delete Account - Sunlight Academy{% endblock %}

{% block content %}
	<h2>Delete your account</h2>

	<p>Last chance. If you click the button below, your account and all associated data will be <strong>permanently deleted</strong>. Click wisely.</p>

	<form action="/account/delete/" method="post">
		{% csrf_token %}
		<input type="hidden" name="iamreallysure" value="iknowwhatiamdoing">
		<input type="submit" value="Permanently Delete Account" class="btn btn-danger">
	</form>

{% endblock %}

sunlightacademy/templates/account_error.html
{% extends "base-full.html" %}

{% block title %}Account Error - Sunlight Academy{% endblock %}

{% block content %}

	<h2>Whoa! Something went wrong</h2>

	<p>Something's up with our servers. Sorry for the inconvenience.</p>

{% endblock %}

sunlightacademy/templates/base-full.html
{% extends "base.html" %}

{% block container %}
    {{ block.super }}
    <div class="row">
        <div class="span12 content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

sunlightacademy/templates/base-old.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="description" content="">

		<meta property="og:site_name" content="Sunlight Academy">
		{% block og %}
	        <meta property="og:title" content="Sunlight Academy">
	        <meta property="og:description" content="">
	        <meta property="og:url" content="http://training.sunlightfoundation.com/">
        {% endblock %}
        <meta property="og:type" content="website">
        <meta property="og:email" content="training@sunlightfoundation.com">
        <meta property="og:image" content="http://s3.amazonaws.com/sunlight-assets/site/4.0/images/opengraph-superhero.jpg">
		<meta property="fb:page_id" content="6921874941">
	    <meta property="og:locale" content="en_US">

		<title>{% block title %}Sunlight Academy{% endblock %}</title>

		<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
		<link rel="stylesheet" href="{% static "css/sunlightacademy.css" %}">

		<style>
			form ul { list-style: none; }
			form > ul > li { margin: 0.3em 0; }
			form ul.errorlist { color: #933; margin: 0; padding: 0; }
			form label { font-weight: bold; }
			.messages ul { list-style: none; margin: 0; padding: 0; }
			.delete-account { text-align: center; }
		</style>
	</head>
	<body class="{% block bodyclass %}internal{% endblock %}">
		<div class="sf-mini-header">
        	<div class="nav">
        		<a class="sf-logo" href="http://www.sunlightfoundation.com">Sunlight Foundation</a>
        		<ul>
        			<li><a href="http://sunlightfoundation.com/about/">About</a></li>
        			<li><a href="http://sunlightfoundation.com/blog/">Blog</a></li>
        			<li><a href="http://sunlightfoundation.com/projects/">Projects</a></li>
        			<li><a href="http://sunlightfoundation.com/contact/">Contact</a></li>
        		</ul>
        	</div>
        </div>
		<div class="container">
			<div id="main-header" class="clearfix">
				<h1><a href="/">Sunlight Academy</a></h1>
				{% block header-nav %}
					<div class="nav">
		                <ul class="account">
		                	{% if request.user.is_authenticated %}
								<li><a href="/account/logout/" class="btn btn-inverse">Logout</a></li>
								<li class="last"><a href="/account/" class="btn btn-inverse"><i class="icon-white icon-user"></i> Account Settings</a></li>
								{% if request.user.is_staff %}
									<li><a href="/admin/" class="btn btn-inverse"><i class="icon-cog icon-white"></i> Admin</a></li>
								{% endif %}
							{% else %}
		                    	<li class="last"><a href="/account/login/" class="btn btn-inverse">Log In</a></li>
							{% endif %}
		                </ul>
		                <ul class="social">
		                    <li class="youtube"><a href="#">YouTube</a></li>
		                    <li class="twitter"><a href="#">Twitter</a></li>
		                    <li class="facebook"><a href="#">Facebook</a></li>
		                </ul>
		            </div>
	            {% endblock %}
			</div>
			{% if messages %}
				<div class="messages">
					<ul>
						{% for message in messages %}
							<li class="alert alert-success">{{ message }}</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% block container %}{% endblock %}
			<div class="footer row">
				<div class="span6 signup">
					<h4>Like this Project and Want to Discover Others Like It?</h4>
		            <form action="/subscribe/" method="post" id="subscribe">
		            	<span class="tip">Join the Sunlight Foundation's open government community to learn more.</span>
		            	{% csrf_token %}
		            	<ul>
		                	<li><input type="text" name="email" placeholder="your email address"></li>
		                	<li><input type="text" name="zipcode" placeholder="your zip code"></li>
		                	<li><button type="submit" class="btn btn-inverse"><i class="icon-envelope icon-white"></i> Sign Up</button></li>
		                </ul>
		            </form>
		            <div class="subscribe-thanks"><p></p></div>
				</div>
				<div class="span5 terms">
					<p>Our <a href="http://sunlightfoundation.com/legal/privacy/">privacy policy</a> details how personally identifiable information that is collected on our web sites is handled. Read our <a href="http://sunlightfoundation.com/legal/terms/">terms of service</a>.</p>
		            <p>This work by <a href="http://sunlightfoundation.com">Sunlight Foundation</a>, unless <a href="http://sunlightfoundation.com/colophon/">otherwise noted</a>, is licensed under a <a href="http://creativecommons.org/licenses/by/3.0/us/">Creative Commons Attribution 3.0 United States License</a>.</p>
				</div>
			</div>
		</div>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	    <script src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=sunlightfoundation"></script>
	    <script src="{% static "js/jquery-1.7.1.min.js" %}"></script>
	    <script src="{% static "js/theacademy.js" %}"></script>
		{% block js %}{% endblock %}
	</body>
</html>

sunlightacademy/templates/base-sidebar.html
{% extends "base.html" %}

{% block container %}
    {{ block.super }}
    <div class="row">
        <div class="span9 content">
            {% block content %}{% endblock %}
        </div>
        <div class="span3 sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
{% endblock %}

sunlightacademy/templates/base.html
<!doctype html>
{% load staticfiles %}
<html class="bb_wrapper">
    <head>
        <meta charset="utf-8">
        {% block og %}
		    <meta property="og:title" content="{{ module.title }}">
		    <meta property="og:description" content="Sunlight Foundation's interactive portal for journalists, activists, researchers and students to explore our tools and develop skill sets to unlock government data.">
		    <meta property="og:url" content="http://training.sunlightfoundation.com/">
		{% endblock %}

        <title>{% block title %}{% endblock %}</title>

        {% block head %}
        	<link rel="shortcut icon" href="http://sunlight-assets.s3.amazonaws.com/academy/favicon.ico">
        {% endblock %}

        <link rel="stylesheet" href="{% static 'sfapp/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'sfapp/css/sfapp.css' %}">
        <link rel="stylesheet" href="https://sunlight-cdn.s3.amazonaws.com/brandingbar/0.3/css/brandingbar.css">
        <link rel="stylesheet" href="https://sunlight-cdn.s3.amazonaws.com/sf-icons/0.2/css/sf-icons.css">
        <!--[if IE 8]>
    		<script src="https://sunlight-cdn.s3.amazonaws.com/sf-icons/0.2/js/sf-icons.js"></script>
		<![endif]-->

        {% block css %}
		    <link rel="stylesheet" href="{% static "css/sunlightacademy.css" %}">
		    <style>
		    	.doormat {
		    		background-color: #fafaf7;
		    		border: 1px solid #ECE9E9;
		    		box-shadow: 0 0 2px #d9d9d9;
		    		color: #666;
		    		font-size: 110%;
		    		margin-bottom: 4em;
		    		text-align: center;
		    		padding: 1em 0;
		    		width: 100%;
		    	}
		   	</style>
		{% endblock %}

        <script type="text/javascript" src="http://use.typekit.com/tab6neo.js"></script>
        <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

        {% if not debug %}
	        <script>
	            var _gaq = _gaq || [];
	            _gaq.push(['_setAccount', 'UA-22821126-23']);
	            _gaq.push(['_trackPageview']);
	            (function() {
	                var ga = document.createElement('script');
	                ga.type = 'text/javascript';
	                ga.async = true;
	                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	                var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga, s);
	            })();

	            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			    ga('create', 'UA-48789618-1', 'training.sunlightfoundation.com');
			    ga('send', 'pageview');
	        </script>
        {% endif %}

    </head>
    <body class="{% block bodyclass %}internal{% endblock %}">

    	<div class="branding-bar" data-bb-brandingbar="true" data-bb-property-id="sunlightlabs-awesome"></div>

        <div class="container">
			{% block container %}
			    <div id="main-header" class="clearfix">
			        {% block header-nav %}
			            <div class="nav">
			                <ul class="account listNav unstyled">
			                    {% if request.user.is_authenticated %}
			                        <li><a href="/account/logout/">Logout</a></li>

			                        <li><a href="/about/">About</a></li>
			                        <li><a href="/events/">Training Events</a></li>
			                        <li {% if not request.user.is_staff %}class="first"{% endif %}><a href="/account/"><i class="icon-white icon-user"></i> Account Settings</a></li>
			                        {% if request.user.is_staff %}
			                            <li class="first"><a href="/admin/"><i class="icon-cog icon-white"></i> Admin</a></li>
			                        {% endif %}
			                    {% else %}
			                        <li class="first"><a href="/account/login/">Log In</a></li>
			                    {% endif %}
			                </ul>
			            </div>
			        {% endblock %}
			        <h1><a href="/">Sunlight Academy</a></h1>
			    </div>
			    {% if messages %}
			        <div class="messages">
			            <ul>
			                {% for message in messages %}
			                    <li class="alert alert-success">{{ message }}</li>
			                {% endfor %}
			            </ul>
			        </div>
			    {% endif %}
			    {% if request.show_doormat %}
					<div class="doormat">
						We need your feedback to make Sunlight Academy better! <a href="https://www.surveymonkey.com/s/SunlightAcademy">Take this quick survey.</a>
					</div>
				{% endif %}
			    <div id="fb-root"></div>
			{% endblock %}
        </div>

        <div class="sf-footerWrapper">
            <div class="sf-footer container">
                <div class="row">
                    <div class="span6 signup span-divider">
                        <h4>Like this Project and Want to Discover Others Like It?</h4>
                        <span class="tip">Join the Sunlight Foundation's open government community to learn more</span>
                        <form action="/subscribe/" method="post" id="sfapp-subscribe-form" class="form-inline">
                            {% csrf_token %}
                            <input type="hidden" name="response" value="json">
                            <input type="text" name="email" placeholder="your email address">
                            <input type="text" name="zipcode" placeholder="your zip code">
                            <button type="submit" class="btn btn-sunlight">Sign Up</button>
                        </form>
                    </div>
                    <div class="span6 terms">
                        <p>Our <a href="http://sunlightfoundation.com/legal/privacy/">privacy policy</a> details how personally identifiable information that is collected on our web sites is handled. Read our <a href="http://sunlightfoundation.com/legal/terms/">terms of service</a>.</p>
                        <p>This work by <a href="http://sunlightfoundation.com">Sunlight Foundation</a>, unless <a href="http://sunlightfoundation.com/colophon/">otherwise noted</a>, is licensed under a <a href="http://creativecommons.org/licenses/by/3.0/us/">Creative Commons Attribution 3.0 United States License</a>.</p>
                    </div>
                </div>
            </div>
        </div>

        <script src="{% static 'sfapp/js/jquery-1.8.3.min.js' %}"></script>
        <script src="{% static 'sfapp/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'sfapp/js/sfapp.js' %}"></script>
        <script src="https://sunlight-cdn.s3.amazonaws.com/brandingbar/0.3/js/brandingbar.min.js.gz"></script>
        {% block js %}
		    <script src="{% static "js/theacademy.js" %}"></script>
		    <script src="https://s3.amazonaws.com/assets.sunlightfoundation.com/social/scripts/simple-socialite-pack.min.js" async></script>
		{% endblock %}

    </body>
</html>

sunlightacademy/templates/category.html
{% extends "base-full.html" %}
{% load staticfiles %}

{% block title %}{{ category.name }} - Sunlight Academy{% endblock %}

{% block content %}
    <div class="module">
	    <h2>Training Modules: {{ category.name }}</h2>
	    <ul class="trainings unstyled clearfix">
	    	{% for module in modules %}
				<li>
					{% if module.pk in completed_ids %}
						<span class="status accomplished">Accomplished</span>
					{% else %}
						<span class="status">Watch</span>
					{% endif %}
		            <a href="{% url 'training_module' module.slug %}">
						{% if module.thumbnail %}
		            		<img src="{{ module.thumbnail.url }}">
		            	{% else %}
		            		<img src="{% static "img/testVideo.jpg" %}">
		            	{% endif %}
		            </a>
		            <div class="description">
		                <div class="clearfix"></div>
		                <h4 title="Legislative Data" class="withTip"><a href="{% url 'training_module' module.slug %}">{{ module.title }}</a></h4>
		                {% if module.date %}
		                	<span class="datetime">{{ module.date.date }}</span>
		                {% endif %}
		                <p class="tip">{{ module.description }}</p>
		                {% with module.categories.all as cats %}
		                	{% if cats|length > 1 %}
			                	<div class="cats">
			                		<span class="tip cat also">Also in:</span>
			                		{% for cat in cats %}
			                			{% if cat != category %}
				                    		<a class="tip cat" href="{% url 'training_category' cat.slug %}">
				                    			{{ cat.name }}
				                    		</a>
			                    		{% endif %}
		                			{% endfor %}
			                	</div>
			                {% endif %}
			            {% endwith %}
		            </div>
				</li>
			{% endfor %}
	    </ul>
    </div>
{% endblock %}

sunlightacademy/templates/comingsoon.html
{% extends "base-full.html" %}
{% load staticfiles %}

{% block title %}Sunlight Academy Coming Soon!{% endblock %}

{% block css %}
	{{ block.super }}
	<style>
		.other-projects-container { margin-top: 4em; }
		.other-projects { list-style: none; margin: 0; padding: 0; }
		.other-projects li { clear: both; margin: 0 0 4em 0; padding: 0; height: 120px; }
		.other-projects img { float: left; margin-right: 2em; width: 60px; }
		.other-projects a h4 { color: #C9A706; margin-bottom: 0.3em; }
		.other-projects p { margin: 0 20px 0 85px; }
	</style>
{% endblock %}

{% block content %}

	<h3>Thank you for signing up!</h3>
	<p>We will send you an email notification when the training portal is live.</p>
	<p>Until then, check out some of Sunlight's other great tools.</p>

	<div class="row other-projects-container">

		<div class="span4">
			<ul class="other-projects">
				<li>
					<a href="http://scout.sunlightfoundation.com"><img src="{% static "img/projects/scout.png" %}"></a>
					<a href="http://scout.sunlightfoundation.com"><h4>Scout</h4></a>
					<p>Scout is a rapid notification service allows anyone to create customized email or text alerts on actions Congress takes on an issue or a specific bill.</p>
				</li>
				<li>
					<a href="http://politicalpartytime.org"><img src="{% static "img/projects/partytime.png" %}"></a>
					<a href="http://politicalpartytime.org"><h4>Party Time</h4></a>
					<p>Party Time documents the Congressional Fundraising Circuit.</p>
				</li>
			</ul>
		</div>

		<div class="span4">

			<ul class="other-projects">
				<li>
					<a href="http://influenceexplorer.com"><img src="{% static "img/projects/ie.png" %}"></a>
					<a href="http://influenceexplorer.com"><h4>Influence Explorer</h4></a>
					<p>Influence Explorer connects the dots of political contributions on the federal and state level.</p>
				</li>
				<li>
					<a href="http://openstates.org"><img src="{% static "img/projects/openstates.png" %}"></a>
					<a href="http://openstates.org"><h4>Open States</h4></a>
					<p>Open States aggregates legislative data directly from state legislatures.</p>
				</li>
			</ul>

		</div>

		<div class="span4">

			<ul class="other-projects">
				<li>
					<a href="http://politiwidgets.com"><img src="{% static "img/projects/politiwidgets.png" %}"></a>
					<a href="http://politiwidgets.com"><h4>Politiwidgets</h4></a>
					<p>Politiwidgets makes inserting information on a Member of Congress into a blog post as easy as embedding a YouTube video.</p>
				</li>
			</ul>

		</div>

	</div>

{% endblock %}